<a href="https://colab.research.google.com/github/danielarruda1000/Data-Science---Study-Cases/blob/master/Content_Bades_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [6]:
from pprint import pprint

In [ ]:
#each row represent a user ['a','b', 'c', 'd']
#each column represent a movie ['Start wars', 'Dark Knight','Shrek','The Incridibles','Bleu','HP']

In [5]:
user_movies = tf.constant([[4,6,8,0,0],
                           [0,0,10,0,8],
                           [0,6,0,0,3],
                           [10,9,0,5,0]])

In [7]:
pprint(user_movies)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[ 4,  6,  8,  0,  0],
       [ 0,  0, 10,  0,  8],
       [ 0,  6,  0,  0,  3],
       [10,  9,  0,  5,  0]], dtype=int32)>


In [8]:
# The columns represent ['Action', 'Sci-fi','Comedy', 'Cartoon','Drame']
movies_feats = tf.constant([[1,1,0,0,1],
                            [1,1,0,0,0],
                            [0,0,1,1,0],
                            [1,0,1,1,0],
                            [0,0,0,0,1]])

In [9]:
pprint(movies_feats)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[1, 1, 0, 0, 1],
       [1, 1, 0, 0, 0],
       [0, 0, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)>


In [17]:
user_movies.shape[0]

4

In [20]:
wgtd_features_matrices = [tf.expand_dims(tf.transpose(user_movies)[:,i],axis=1) * movies_feats for i in range(user_movies.shape[0])]

In [22]:
wgtd_features_matrices

[<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
 array([[4, 4, 0, 0, 4],
        [6, 6, 0, 0, 0],
        [0, 0, 8, 8, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=int32)>,
 <tf.Tensor: shape=(5, 5), dtype=int32, numpy=
 array([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0, 10, 10,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  8]], dtype=int32)>,
 <tf.Tensor: shape=(5, 5), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0],
        [6, 6, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 3]], dtype=int32)>,
 <tf.Tensor: shape=(5, 5), dtype=int32, numpy=
 array([[10, 10,  0,  0, 10],
        [ 9,  9,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 5,  0,  5,  5,  0],
        [ 0,  0,  0,  0,  0]], dtype=int32)>]

In [23]:
user_movies_feats = tf.stack(wgtd_features_matrices, axis=0)

In [24]:
user_movies_feats #(shape = num users, moveis, features)

<tf.Tensor: shape=(4, 5, 5), dtype=int32, numpy=
array([[[ 4,  4,  0,  0,  4],
        [ 6,  6,  0,  0,  0],
        [ 0,  0,  8,  8,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0]],

       [[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0, 10, 10,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  8]],

       [[ 0,  0,  0,  0,  0],
        [ 6,  6,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  3]],

       [[10, 10,  0,  0, 10],
        [ 9,  9,  0,  0,  0],
        [ 0,  0,  0,  0,  0],
        [ 5,  0,  5,  5,  0],
        [ 0,  0,  0,  0,  0]]], dtype=int32)>

In [28]:
# Normalize

#1) Sum movie feats
user_movies_feats_sum = tf.reduce_sum(user_movies_feats, axis=1)

#2) Total
user_movies_feats_totals = tf.reduce_sum(user_movies_feats_sum, axis=1)

In [26]:
user_movies_feats_sum

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[10, 10,  8,  8,  4],
       [ 0,  0, 10, 10,  8],
       [ 6,  6,  0,  0,  3],
       [24, 19,  5,  5, 10]], dtype=int32)>

In [31]:
user_movies_feats_totals

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([40, 28, 15, 63], dtype=int32)>

In [39]:
user_feats = tf.stack([user_movies_feats_sum[i,:]/user_movies_feats_totals[i] for i in range(user_movies.shape[0])], axis=0)

In [40]:
user_feats

<tf.Tensor: shape=(4, 5), dtype=float64, numpy=
array([[0.25      , 0.25      , 0.2       , 0.2       , 0.1       ],
       [0.        , 0.        , 0.35714286, 0.35714286, 0.28571429],
       [0.4       , 0.4       , 0.        , 0.        , 0.2       ],
       [0.38095238, 0.3015873 , 0.07936508, 0.07936508, 0.15873016]])>

In [44]:
# Rating filmes
user_ratings = [tf.map_fn(lambda x: tf.tensordot(user_feats[i], x, axes=1),
                          tf.cast(movies_feats, tf.float64))
                for i in range(user_movies.shape[0])]

In [46]:
all_users_ratings = tf.stack(user_ratings)

In [47]:
all_users_ratings

<tf.Tensor: shape=(4, 5), dtype=float64, numpy=
array([[0.6       , 0.5       , 0.4       , 0.65      , 0.1       ],
       [0.28571429, 0.        , 0.71428571, 0.71428571, 0.28571429],
       [1.        , 0.8       , 0.        , 0.4       , 0.2       ],
       [0.84126984, 0.68253968, 0.15873016, 0.53968254, 0.15873016]])>